### ISSUE TITLE
这个组件是否适合ui-router？

### ISSUE THREAD

**Issue by hanyou** [Allen-Wei/angular-alan-auth#1]
看demo使用的ngRoute，是否适合ui-router？

**Comment by alanwei43** [comment]
@hanyou 已加上对`ui-router`的支持, 这里是[demo](http://github.alanwei.net/angular-alan-auth/ui.router/app.html), 你需要引用 `https://github.com/Allen-Wei/angular-alan-auth/blob/master/src/alan-auth.ui-router.js` 这个JS文件(需要下载到本地放到项目里面).
